<a href="https://colab.research.google.com/github/Deepakk200/colab_python/blob/main/Heart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [18]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
import warnings
warnings.filterwarnings('ignore')

In [24]:
heart = pd.read_csv('/content/drive/MyDrive/datasets/Heart.csv')
heart['AHD'] = 1*(heart['AHD'] == "Yes")# Force the response into a binary indicator:

print(heart.shape)
heart_train, heart_val = train_test_split(heart, train_size = 0.75, random_state = 109)

print(heart_train.shape, heart_val.shape)

x_train = heart_train[['Age']]
y_train = heart_train['AHD']


(303, 15)
(227, 15) (76, 15)


In [25]:

knn20 = KNeighborsClassifier( n_neighbors = 20 )
knn20.fit(x_train , y_train)
yhat20_class = knn20.predict(x_train)
yhat20_prob = knn20.predict_proba(x_train)

# print out the first 10 predictions for the actual data
print(yhat20_class[1:10])
print(yhat20_prob[1:10])

[0 1 1 1 0 1 1 0 1]
[[0.75 0.25]
 [0.4  0.6 ]
 [0.25 0.75]
 [0.3  0.7 ]
 [0.65 0.35]
 [0.45 0.55]
 [0.35 0.65]
 [0.7  0.3 ]
 [0.35 0.65]]


In [28]:
logit1 = LogisticRegression(penalty=None, max_iter = 1000)

logit1.fit(x_train,y_train)


print("Logistic Regression Estimated Betas (B0,B1):",logit1.intercept_, logit1.coef_[0])
logit1.predict_proba(x_train)

Logistic Regression Estimated Betas (B0,B1): [-3.32616703] [0.05933142]


array([[0.68458335, 0.31541665],
       [0.70962816, 0.29037184],
       [0.48607262, 0.51392738],
       [0.44183498, 0.55816502],
       [0.42725744, 0.57274256],
       [0.5599436 , 0.4400564 ],
       [0.37042936, 0.62957064],
       [0.41280515, 0.58719485],
       [0.54527607, 0.45472393],
       [0.50090187, 0.49909813],
       [0.47126785, 0.52873215],
       [0.45651346, 0.54348654],
       [0.35670215, 0.64329785],
       [0.47126785, 0.52873215],
       [0.61733664, 0.38266336],
       [0.48607262, 0.51392738],
       [0.67163396, 0.32836604],
       [0.68458335, 0.31541665],
       [0.3843692 , 0.6156308 ],
       [0.34320632, 0.65679368],
       [0.45651346, 0.54348654],
       [0.58894264, 0.41105736],
       [0.45651346, 0.54348654],
       [0.69725226, 0.30274774],
       [0.44183498, 0.55816502],
       [0.73345861, 0.26654139],
       [0.5599436 , 0.4400564 ],
       [0.53052956, 0.46947044],
       [0.5599436 , 0.4400564 ],
       [0.32995921, 0.67004079],
       [0.

In [30]:
# Define the equivalent validation variables from `heart_val`
x_val = heart_val[['Age']]
y_val = heart_val['AHD']
knn20_train_accuracy = knn20.score(x_train, y_train)
knn20_val_accuracy  = knn20.score(x_val, y_val)
logit_train_accuracy = logit1.score(x_train, y_train)
logit_val_accuracy = logit1.score(x_val, y_val)
print("k-NN Train & Validation Accuracy:", knn20_train_accuracy, knn20_val_accuracy)
print("Logisitic Train & Validation Accuracy:", logit_train_accuracy, logit_val_accuracy)



k-NN Train & Validation Accuracy: 0.6563876651982379 0.5921052631578947
Logisitic Train & Validation Accuracy: 0.6387665198237885 0.6052631578947368
